# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  thymeleaf.cache: false
  main.show-banner: false

#logging:
#  level:
#    ROOT: DEBUG
#    org.springframework.web: ERROR
##    com.myboot: DEBUG
#    com.myboot: TRACE
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file: ./application.log

